version: '2'


#The primary purpose of this dockerfile is to simply building for production.
#It allows me to simply run docker-compose up and let docker take care of everything else
services:
  # angular: 
  #   build: angular-frontend 
  #   volumes:
  #     - ./angular-frontend:/usr/src/app
  express:
    build: server
    volumes:
      - ./server:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    # volumes:
    #   - /data/mongodb/db:/data/db
    ports:
      - "27018:27017"
